# Generated by Django 2.1.7 on 2019-02-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('user__username',), 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
