# Generated by Django 2.1.5 on 2019-01-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvoters',
            field=models.ManyToManyField(blank=True, null=True, related_name='downvoted_posts', to='posts.Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvoters',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvoted_posts', to='posts.Author'),
        ),
    ]
