# Generated by Django 2.1.5 on 2019-01-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190127_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvoters',
            field=models.ManyToManyField(related_name='downvoted_posts', to='posts.Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvoters',
            field=models.ManyToManyField(related_name='upvoted_posts', to='posts.Author'),
        ),
    ]
